/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 18 12:54:15 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class codeToTest_ESTest extends codeToTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = codeToTest.compare((-1620), 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = codeToTest.compare(0, (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = codeToTest.compare((-1), (-1620));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = codeToTest.compare(1986, 1986);
      assertEquals(1986, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      codeToTest codeToTest0 = new codeToTest();
  }
}
